---
language: node_js
node_js:
  - "12"

dist: xenial

addons:
  chrome: stable

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - npm --version

script:
  - npm run lint:js
  - npm test
